// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntyjzdkkmixwlslftjsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50eWp6ZGtrbWl4d2xzbGZ0anNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1ODUyMDIsImV4cCI6MjA3OTE2MTIwMn0.beqg-_W7ddLAPNT7aTEmruFgNksDP0BMhrTxaxNcFkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});